# based on the work from rigon (https://github.com/rigon/docker-sharelatex-full)
FROM sharelatex/sharelatex:latest

SHELL ["/bin/bash", "-cx"]


# CODE Server
RUN curl -fsSL https://code-server.dev/install.sh | sh
RUN mkdir -p /var/lib/codeserver
# ENTRYPOINT "/usr/bin/code-server" "/var/lib/codeserver" "--bind-addr=0.0.0.0:8090" & "/sbin/my_init"
ENTRYPOINT "/usr/bin/code-server" "/var/lib/codeserver" "--bind-addr=0.0.0.0:8090" "--config=/root/.config/code-server/.config" & "/sbin/my_init"



