name: test build

on:
  pull_request:
    paths:
      - docker/use/0Dockerfile
      - docker/use/1Dockerfile.code
      - docker/use/0Dockerfile.full
      - docker/use/0Dockerfile.full.code
      - docker/use/0Dockerfile.full.cn
      - docker/use/0Dockerfile.full.cn.code
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: test build
      uses: docker/build-push-action@v4
      with:
        push: false
